import sendEmail from "./emailService.js";
import { generateOTPCode } from "./generateOTP.js";

// Helper function to send OTP
export const sendOTP = async (user) => {
    const newOTP = generateOTPCode();
    const otpExpiry = new Date();
    otpExpiry.setSeconds(otpExpiry.getSeconds() + 600);
  
    user.otp = newOTP;
    user.otp_expiry = otpExpiry;
    await user.save();
  
    // Sending email with OTP
    await sendEmail({
      email: user.email,
      subject: "Resend Code",
      message: `Dear ${user.firstName},\n\nOTP request action is triggered for your account.\n\nYour OTP code is: ${newOTP}.\n\nDo not share your OTP with anyone.\n\nIf you face any difficulty during the registration process, get in touch with our Support team.\n\nThis email was auto-generated by HimalayanBazar Marketplace. Please do not reply to this mail.\n\nRegards,\nHimalayanBazar Team`,
    });
  };